//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "commentt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub comment_id: String,
    pub user_id: String,
    pub target_id: String,
    pub target_type: i16,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub parent_id: Option<String>,
    pub created: i64,
    pub updated: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
