//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dict")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub dict_code: String,
    pub dict_name: String,
    pub parent_code: Option<String>,
    pub remark: Option<String>,
    pub status: i16,
    pub created: i64,
    pub updated: Option<i64>,
    pub public: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
