//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod commentt;
pub mod config;
pub mod dict;
pub mod dict_item;
pub mod favorite;
pub mod follow;
pub mod group;
pub mod likee;
pub mod role;
pub mod score;
pub mod social_report;
pub mod user;
pub mod user_app;
pub mod user_device;
pub mod user_feed_back;
pub mod user_group;
pub mod user_role;
pub mod user_vip_level;
