//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::commentt::Entity as Commentt;
pub use super::config::Entity as Config;
pub use super::dict::Entity as Dict;
pub use super::dict_item::Entity as DictItem;
pub use super::favorite::Entity as Favorite;
pub use super::follow::Entity as Follow;
pub use super::group::Entity as Group;
pub use super::likee::Entity as Likee;
pub use super::role::Entity as Role;
pub use super::score::Entity as Score;
pub use super::social_report::Entity as SocialReport;
pub use super::user::Entity as User;
pub use super::user_app::Entity as UserApp;
pub use super::user_device::Entity as UserDevice;
pub use super::user_feed_back::Entity as UserFeedBack;
pub use super::user_group::Entity as UserGroup;
pub use super::user_role::Entity as UserRole;
pub use super::user_vip_level::Entity as UserVipLevel;
