//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "social_report")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub target_id: String,
    pub target_type: i16,
    pub like_count: i64,
    pub follow_count: i64,
    pub favorite_count: i64,
    pub comment_count: i64,
    pub score_count: i64,
    pub score_total: i64,
    pub created: i64,
    pub updated: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
